version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/home/node/app
    command:  /home/node/app/node_modules/.bin/nodemon server.js 
    